name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest coverage  # Certifique-se de que coverage está instalado
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip list  # Listar pacotes instalados para verificação

    - name: Verificando instalação do Coverage
      run: python -m pip show coverage  # Verificar se coverage está instalado

    - name: Conectando com a IA
      run: python -m coverage run analytics/script_IA_integracao  # Ajuste o caminho se necessário

    - name: Relatório do teste
      run: python -m coverage report -a  # Usando python -m para chamar coverage

    - name: Deploy no EC2 - AWS
      run: |
        echo "Conectando no EC2"
        echo "${{ secrets.AWS_INDESPENSA_VENV }}" > private_key &&
        chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ubuntu@ec2-44-218-89-231.compute-1.amazonaws.com "
        cd analytics/ &&
        cd regulated-foods/ &&
        git pull &&
        ./executar.sh"
